from typing import Protocol


class InstagramPort(Protocol):
    async def login(self, session: dict | None) -> dict | None: ...

    async def send_message(self, text: str, username: str) -> None: ...

    async def follow_user(self, user_id: int) -> None: ...

    async def like_post(self, post_id: int) -> None: ...


class FilesPort(Protocol):
    async def load_instagram_session(self) -> dict | None: ...

    async def save_instagram_session(self, session: dict) -> None: ...
